### ISSUE TITLE
Cannot run HelloWorld example with Scala 2.10.4 / Finch 0.10.0

### ISSUE THREAD

**Issue by chrisbenincasa** [finagle/finch#604]
Hello, I'm unable to compile and run the Hello World example with Scala 2.10.4. Apologizes if this version is not supported, although I am able to download finch_core-2.10@0.10.0 from Maven Central.

When trying to compile a simple App with the Hello World example from the README:

```
finch-test ) sbt run
[info] Loading project definition from /Users/christianbenincasa/Dev/scala/finch-test/project
[info] Set current project to finch-test (in build file:/Users/christianbenincasa/Dev/scala/finch-test/)
[info] Compiling 1 Scala source to /Users/christianbenincasa/Dev/scala/finch-test/target/scala-2.10/classes...
[error] /Users/christianbenincasa/Dev/scala/finch-test/src/main/scala/com/chrisbenincasa/HelloWorld.scala:14: overloaded method value apply with alternatives:
[error]   (mapper: io.finch.internal.Mapper[shapeless.HNil])io.finch.Endpoint[mapper.Out] <and>
[error]   (input: io.finch.Input)io.finch.Endpoint.Result[shapeless.HNil]
[error]  cannot be applied to (io.finch.Output[String])
[error]   val api: Endpoint[String] = get("hello") { Ok("Hello, World!") }
[error]                                  ^
[error] one error found
[error] (compile:compileIncremental) Compilation failed
[error] Total time: 2 s, completed Jun 10, 2016 2:23:07 PM
```

It works fine with 2.11.x

```
finch-test ) sbt update run
[info] Loading project definition from /Users/christianbenincasa/Dev/scala/finch-test/project
[info] Set current project to finch-test (in build file:/Users/christianbenincasa/Dev/scala/finch-test/)
[info] Updating {file:/Users/christianbenincasa/Dev/scala/finch-test/}finch-test...
[info] Resolving jline#jline;2.11 ...
[info] Done updating.
[warn] Scala version was updated by one of library dependencies:
[warn]  * org.scala-lang:scala-library:(2.11.0, 2.11.6) -> 2.11.7
[warn] To force scalaVersion, add the following:
[warn]  ivyScala := ivyScala.value map { _.copy(overrideScalaVersion = true) }
[warn] Run 'evicted' to see detailed eviction warnings
[success] Total time: 1 s, completed Jun 10, 2016 2:27:18 PM
[info] Compiling 1 Scala source to /Users/christianbenincasa/Dev/scala/finch-test/target/scala-2.11/classes...
[info] 'compiler-interface' not yet compiled for Scala 2.11.0. Compiling...
[info]   Compilation completed in 11.3 s
[info] Running com.chrisbenincasa.HelloWorld 
Jun 10, 2016 2:27:30 PM com.twitter.finagle.Init$$anonfun$1 apply$mcV$sp
INFO: Finagle version 6.33.0 (rev=21d0ee8b5070b735eda5c84d7aa6fbf1ba7b1635) built at 20160203-202859
[success] Total time: 13 s, completed Jun 10, 2016 2:27:31 PM
```

The main class:
```scala
//
// HelloWorld.scala
//

package com.chrisbenincasa

import io.finch._
import com.twitter.finagle.Http

object HelloWorld extends App {

  val api: Endpoint[String] = get("hello") { Ok("Hello, World!") }

  Http.serve(":8080", api.toService)
}
```

and build.sbt (swap scalaVersion with 2.10.4 for the former example):
```scala
name := "finch-test"

version := "1.0"

scalaVersion := "2.11.0"

mainClass in (Compile, run) := Some("com.chrisbenincasa.HelloWorld")

libraryDependencies ++= Seq(
  "com.github.finagle" %% "finch-core" % "0.10.0"
)
```

Any help would be greatly appreciated!

**Comment by vkostyukov** [comment]
Hi @chrisbenincasa! Any chance you can try using 2.10.6? This is the version Finch is compiled today and *I think* you should be able to compile your code with it.

**Comment by vkostyukov** [comment]
I have a long term plan to get rid of `Mapper` (and fix this issue), but I'm not sure how critical is that given that the next Finch release (0.11) will be the last one supporting Scala 2.10. We should do that if we want to stay aligned with the Finagle version (6.35 was the last 2.10 release - see http://finagle.github.io/blog/2016/04/20/scala-210-and-java7/).

**Comment by chrisbenincasa** [comment]
Thanks for the quick reply @vkostyukov!

Just tried with 2.10.6 and got the same error:

```
finch-test ) sbt update run
[info] Loading project definition from /Users/christianbenincasa/Dev/scala/finch-test/project
[info] Set current project to finch-test (in build file:/Users/christianbenincasa/Dev/scala/finch-test/)
[info] Updating {file:/Users/christianbenincasa/Dev/scala/finch-test/}finch-test...
[info] Resolving org.fusesource.jansi#jansi;1.4 ...
[info] Done updating.
[success] Total time: 2 s, completed Jun 10, 2016 2:47:50 PM
[info] Updating {file:/Users/christianbenincasa/Dev/scala/finch-test/}finch-test...
Waiting for lock on /Users/christianbenincasa/.ivy2/.sbt.ivy.lock to be available...
[info] Resolving org.fusesource.jansi#jansi;1.4 ...
[info] Done updating.
[info] Compiling 1 Scala source to /Users/christianbenincasa/Dev/scala/finch-test/target/scala-2.10/classes...
Waiting for lock on /Users/christianbenincasa/.ivy2/.sbt.ivy.lock to be available...
[info] 'compiler-interface' not yet compiled for Scala 2.10.6. Compiling...
[info]   Compilation completed in 16.596 s
[error] /Users/christianbenincasa/Dev/scala/finch-test/src/main/scala/com/chrisbenincasa/HelloWorld.scala:14: overloaded method value apply with alternatives:
[error]   (mapper: io.finch.internal.Mapper[shapeless.HNil])io.finch.Endpoint[mapper.Out] <and>
[error]   (input: io.finch.Input)io.finch.Endpoint.Result[shapeless.HNil]
[error]  cannot be applied to (io.finch.Output[String])
[error]   val api: Endpoint[String] = get("hello") { Ok("Hello, World!") }
[error]                                  ^
[error] one error found
[error] (compile:compileIncremental) Compilation failed
[error] Total time: 20 s, completed Jun 10, 2016 2:48:09 PM
```

And the updated build.sbt (just the version bump)
```scala
name := "finch-test"

version := "1.0"

scalaVersion := "2.10.6"

mainClass in (Compile, run) := Some("com.chrisbenincasa.HelloWorld")

libraryDependencies ++= Seq(
  "com.github.finagle" %% "finch-core" % "0.10.0"
)
```

**Comment by vkostyukov** [comment]
Ok, let's try to add:

```
addCompilerPlugin(
  "org.scalamacros" % "paradise" % "2.1.0" cross CrossVersion.full
)
```

to your `build.sbt` and see if it helps. Otherwise, I'm running out of ideas.

**Comment by chrisbenincasa** [comment]
That worked! Thank you!

**Comment by vkostyukov** [comment]
@chrisbenincasa Happy to help!
